---
# tasks file for mediawiki
#
- name: "Creating yum repo"
  yum_repository:
     baseurl: "http://mirror.centos.org/centos/7/os/x86_64/"
     description: "Centos_yum"
     enabled: yes
     file: "mediawiki"
     name: "new_centos_yum"
     state: present
     gpgcheck: no
- name: "Installing softwares"
  package:
     name: "{{ item }}"
     state: present
  with_items:
    - httpd
    - php
    - php-mysql
    - php-gd
    - mariadb-server
    - php-xml
    - php-intl
    - mysql
    - epel-release
    - python-pip
    - mariadb-devel
    - gcc
    - python-devel
- name: "Starting the services"
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items:
    - httpd
    - mariadb
  ignore_errors: yes
  register: x
- shell: /usr/sbin/httpd && /usr/libexec/mariadb-prepare-db-dir %n
  when: x.failed != "false"
- shell: "/usr/bin/mysqld_safe &"
  when: x.failed != "false"
- name: "Installing mysql-python module"
  pip:
    name: "MySQL-python"
    state: present



